CREATE TABLE `impressions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `impressionable_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impressionable_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `controller_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `view_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `request_hash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip_address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `session_hash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `message` mediumtext COLLATE utf8mb4_unicode_ci,
  `referrer` mediumtext COLLATE utf8mb4_unicode_ci,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `controlleraction_ip_index` (`controller_name`(191),`action_name`(191),`ip_address`(191)) USING BTREE,
  KEY `controlleraction_request_index` (`controller_name`(191),`action_name`(191),`request_hash`(191)) USING BTREE,
  KEY `controlleraction_session_index` (`controller_name`(191),`action_name`(191),`session_hash`(191)) USING BTREE,
  KEY `impressionable_type_message_index` (`impressionable_type`(191),`message`(191),`impressionable_id`) USING BTREE,
  KEY `index_impressions_on_user_id` (`user_id`) USING BTREE,
  KEY `index_impressions_on_created_at` (`created_at`),
  KEY `poly_ip_index` (`impressionable_type`(50),`impressionable_id`,`created_at`,`ip_address`(191)) USING BTREE,
  KEY `poly_request_index` (`impressionable_type`(50),`impressionable_id`,`created_at`,`request_hash`(191)) USING BTREE,
  KEY `poly_session_index` (`impressionable_type`(50),`impressionable_id`,`created_at`,`session_hash`(191)) USING BTREE,
  KEY `index_imp_on_ciir` (`created_at`,`impressionable_type`,`impressionable_id`,`request_hash`),
  KEY `index_imp_on_ciiu` (`created_at`,`impressionable_type`,`impressionable_id`,`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8074 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

 CREATE TABLE `ddt_locations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner_id` int(11) DEFAULT NULL,
  `longitude` decimal(9,6) DEFAULT NULL,
  `latitude` decimal(9,6) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `owner_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sampled_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `owner_location_index` (`owner_id`,`owner_type`,`updated_at`)
) ENGINE=InnoDB AUTO_INCREMENT=214 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ddt_app_notification_caches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) DEFAULT NULL,
  `notification_id` int(11) DEFAULT NULL,
  `notification_event_id` int(11) DEFAULT NULL,
  `notification_action_id` int(11) DEFAULT NULL,
  `message` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `anc_created_at` (`created_at`),
  KEY `notification_cache_account_date` (`account_id`,`created_at`),
  KEY `anc_notification` (`notification_id`),
  KEY `anc_event` (`notification_event_id`),
  KEY `anc_action` (`notification_action_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3111 DEFAULT CHARSET=utf8;

CREATE TABLE `ddt_js_errors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `agent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `error_message` mediumtext COLLATE utf8mb4_unicode_ci,
  `stack_trace` mediumtext COLLATE utf8mb4_unicode_ci,
  `cause` mediumtext COLLATE utf8mb4_unicode_ci,
  `count` int(11) DEFAULT '1',
  `digest` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_js_errors_on_count` (`count`) USING BTREE,
  KEY `index_ddt_js_errors_on_created_at` (`created_at`) USING BTREE,
  KEY `index_ddt_js_errors_on_digest` (`digest`(191)) USING BTREE,
  KEY `index_ddt_js_errors_on_updated_at` (`updated_at`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=494 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ddt_js_error_counts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ip` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `js_error_id` int(11) DEFAULT NULL,
  `count` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_js_error_counts_on_count` (`count`) USING BTREE,
  KEY `index_ddt_js_error_counts_on_js_error_id` (`js_error_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=496 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ;

CREATE TABLE `ddt_message_receptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) DEFAULT NULL,
  `msg_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `msg_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `to_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `from_user_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` int(11) DEFAULT NULL,
  `content` text COLLATE utf8mb4_unicode_ci,
  `media_id` int(11) DEFAULT NULL,
  `pic_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `voice_format` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `thumb_media_id` int(11) DEFAULT NULL,
  `location_x` float DEFAULT NULL,
  `location_y` float DEFAULT NULL,
  `scale` int(11) DEFAULT NULL,
  `label` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `event` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `event_key` text COLLATE utf8mb4_unicode_ci,
  `ticket` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `longitude` decimal(9,6) DEFAULT NULL,
  `latitude` decimal(9,6) DEFAULT NULL,
  `precision` float DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_message_receptions_on_shop_id` (`shop_id`) USING BTREE,
  KEY `index_ddt_message_receptions_on_from_user_name` (`from_user_name`),
  KEY `index_ddt_message_receptions_on_to_user_name` (`to_user_name`),
  KEY `index_ddt_message_receptions_on_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=478 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ddt_message_responses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) DEFAULT NULL,
  `message_reception_id` int(11) DEFAULT NULL,
  `msg_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `to_user_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `from_user_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` int(11) DEFAULT NULL,
  `content` mediumtext COLLATE utf8mb4_unicode_ci,
  `media_id` int(11) DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` mediumtext COLLATE utf8mb4_unicode_ci,
  `music_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hq_music_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `thumb_media_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `article_count` int(11) DEFAULT '0',
  `pic_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_message_responses_on_message_reception_id` (`message_reception_id`) USING BTREE,
  KEY `index_ddt_message_responses_on_shop_id` (`shop_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=194 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

 CREATE TABLE `ddt_message_response_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) DEFAULT NULL,
  `message_response_id` int(11) DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` mediumtext COLLATE utf8mb4_unicode_ci,
  `pic_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_message_response_items_on_message_response_id` (`message_response_id`) USING BTREE,
  KEY `index_ddt_message_response_items_on_shop_id` (`shop_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=313 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ddt_notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) DEFAULT NULL,
  `branch_id` int(11) DEFAULT NULL,
  `notification_target_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notification_target_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `notification_event_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_notifications_on_branch_id` (`branch_id`) USING BTREE,
  KEY `index_ddt_notifications_on_notification_event_id` (`notification_event_id`) USING BTREE,
  KEY `index_ddt_notifications_on_notification_target` (`notification_target_type`(191),`notification_target_id`) USING BTREE,
  KEY `index_ddt_notifications_on_shop_id` (`shop_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8073 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
CREATE TABLE `ddt_notification_actions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) DEFAULT NULL,
  `branch_id` int(11) DEFAULT NULL,
  `notification_id` int(11) DEFAULT NULL,
  `type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` mediumtext COLLATE utf8mb4_unicode_ci,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `cache_view` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `index_ddt_notification_actions_on_branch_id` (`branch_id`) USING BTREE,
  KEY `index_ddt_notification_actions_on_notification_id` (`notification_id`) USING BTREE,
  KEY `index_ddt_notification_actions_on_shop_id` (`shop_id`) USING BTREE,
  KEY `index_ddt_notification_actions_on_type_and_id` (`type`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16680 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ;


CREATE TABLE `ddt_notification_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) DEFAULT NULL,
  `branch_id` int(11) DEFAULT NULL,
  `order_id` int(11) DEFAULT NULL,
  `type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `table_id` int(11) DEFAULT NULL,
  `base_coupon_id` int(11) DEFAULT NULL,
  `order_change_log_id` int(11) DEFAULT NULL,
  `change_table_record_id` int(11) DEFAULT NULL,
  `merge_table_record_id` int(11) DEFAULT NULL,
  `shipment_id` int(11) DEFAULT NULL,
  `guest_queue_id` int(11) DEFAULT NULL,
  `preferences` text COLLATE utf8mb4_unicode_ci,
  `account_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `variant_id` int(11) DEFAULT NULL,
  `wallet_log_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_notification_events_on_branch_id` (`branch_id`) USING BTREE,
  KEY `index_ddt_notification_events_on_order_id` (`order_id`) USING BTREE,
  KEY `index_ddt_notification_events_on_shop_id` (`shop_id`) USING BTREE,
  KEY `index_ddt_notification_events_on_table_id` (`table_id`),
  KEY `index_ddt_notification_events_on_base_coupon_id` (`base_coupon_id`),
  KEY `index_ddt_notification_events_on_order_change_log_id` (`order_change_log_id`),
  KEY `index_ddt_notification_events_on_change_table_record_id` (`change_table_record_id`),
  KEY `index_ddt_notification_events_on_merge_table_record_id` (`merge_table_record_id`),
  KEY `index_ddt_notification_events_on_shipment_id` (`shipment_id`),
  KEY `index_ddt_notification_events_on_guest_queue_id` (`guest_queue_id`),
  KEY `index_ddt_notification_events_on_account_id` (`account_id`),
  KEY `index_ddt_notification_events_on_type_and_id` (`type`,`id`),
  KEY `index_ddt_notification_events_on_updated_at` (`updated_at`),
  KEY `index_ddt_notification_events_on_wallet_log_id` (`wallet_log_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2368 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ddt_print_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) DEFAULT NULL,
  `branch_id` int(11) DEFAULT NULL,
  `printer_id` int(11) DEFAULT NULL,
  `content` mediumtext COLLATE utf8mb4_unicode_ci,
  `times` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `record_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_print_records_on_branch_id` (`branch_id`) USING BTREE,
  KEY `index_ddt_print_records_on_printer_id` (`printer_id`) USING BTREE,
  KEY `index_ddt_print_records_on_shop_id` (`shop_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=352 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ;

CREATE TABLE `ddt_payment_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shop_id` int(11) DEFAULT NULL,
  `branch_id` int(11) DEFAULT NULL,
  `order_id` int(11) DEFAULT NULL,
  `payment_id` int(11) DEFAULT NULL,
  `order_number` varchar(255) DEFAULT NULL,
  `out_trade_no` varchar(255) DEFAULT NULL,
  `amount` decimal(8,2) DEFAULT NULL,
  `payment_method_name` varchar(255) DEFAULT NULL,
  `payment_state` varchar(255) DEFAULT NULL,
  `multi_pay_item` tinyint(1) DEFAULT NULL,
  `event` varchar(255) DEFAULT NULL,
  `extra` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_ddt_payment_logs_on_shop_id` (`shop_id`),
  KEY `index_ddt_payment_logs_on_branch_id` (`branch_id`),
  KEY `index_ddt_payment_logs_on_order_id` (`order_id`),
  KEY `index_ddt_payment_logs_on_payment_id` (`payment_id`),
  KEY `index_ddt_payment_logs_on_order_number` (`order_number`),
  KEY `index_ddt_payment_logs_on_out_trade_no` (`out_trade_no`),
  KEY `index_ddt_payment_logs_on_payment_method_name` (`payment_method_name`),
  KEY `index_ddt_payment_logs_on_payment_state` (`payment_state`),
  KEY `index_ddt_payment_logs_on_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=120 DEFAULT CHARSET=utf8;