test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

development:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: cn-shanghai
  bucket: shh-p
  endpoint: https://oss-cn-shanghai.aliyuncs.com

production:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: cn-shanghai
  bucket: shh-p
  endpoint: https://oss-cn-shanghai.aliyuncs.com

minio:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:minio, :access_key_id) || 'minioadmin' %>
  secret_access_key: <%= Rails.application.credentials.dig(:minio, :secret_access_key) || 'minioadmin' %>
  region: us-east-1
  bucket: diandantong
  endpoint: http://localhost:9000
  force_path_style: true
