class FixDecimalPrecision < ActiveRecord::Migration
  def change
    decimal_columns = [
      # {table: :abstract_coupon_versions, column: :groupon_price, other_options: {default: 10.0}},
      # {table: :abstract_coupon_versions, column: :norminal_value, other_options: {default: 10.0}},
      # {table: :abstract_coupon_versions, column: :coupon_min_usable_amount, other_options: {default: 100.0}},
      # {table: :abstract_sources, column: :amount, other_options: {default: 0.0}},
      # {table: :adjustments, column: :amount, other_options: {default: 0.0}},
      # {table: :agents, column: :balance, other_options: {default: 0.0}},
      # {table: :agents, column: :mini_store_price, other_options: {}},
      # {table: :agents, column: :standard_store_price, other_options: {}},
      # {table: :agents, column: :chain_start_price, other_options: {}},
      # {table: :base_users, column: :total_amount, other_options: {default: 0.0}},
      # {table: :call_settings, column: :amount, other_options: {default: 0.5}},
      # {table: :call_settings, column: :used_amount, other_options: {default: 0.0}},
      # {table: :combo_items, column: :price, other_options: {default: 0.0}},
      # {table: :combo_items, column: :vip_price, other_options: {default: 0.0}},
      # {table: :combo_items, column: :original_price, other_options: {default: 0.0}},
      # {table: :combo_items_variants, column: :price, other_options: {default: 0.0}},
      # {table: :combo_items_variants, column: :vip_price, other_options: {default: 0.0}},
      # {table: :combo_items_variants, column: :original_price, other_options: {default: 0.0}},
      # {table: :combo_package_items, column: :price, other_options: {default: 0.0}},
      # {table: :combo_package_items, column: :vip_price, other_options: {default: 0.0}},
      # {table: :combo_package_items, column: :original_price, other_options: {default: 0.0}},
      # {table: :combos, column: :price, other_options: {}},
      # {table: :combos, column: :vip_price, other_options: {}},
      # {table: :deductions, column: :amount, other_options: {}},
      # {table: :deductions, column: :cash_amount, other_options: {default: 0.0}},
      # {table: :deductions, column: :extra_amount, other_options: {default: 0.0}},
      # {table: :delivery_ranges, column: :cost, other_options: {default: 0.0}},
      # {table: :delivery_settings, column: :support_delivery_if_amount_gt, other_options: {default: 10.0}},
      # {table: :delivery_settings, column: :charge_delivery_fee_if_amount_lt, other_options: {default: 100.0}},
      # {table: :delivery_settings, column: :min_delivery_fee, other_options: {default: 0.0}},
      # {table: :delivery_settings, column: :per_unit_cost, other_options: {default: 0.0}},
      # {table: :delivery_times, column: :cost, other_options: {default: 0.0}},
      # {table: :delivery_zones, column: :cost, other_options: {default: 0.0}},
      # {table: :groupon_line_items, column: :price, other_options: {}},
      # {table: :groupon_line_items, column: :groupon_price, other_options: {}},
      # {table: :line_items, column: :price, other_options: {}},
      # {table: :line_items, column: :vip_price, other_options: {}},
      # {table: :line_items, column: :original_price, other_options: {}},
      # {table: :line_items, column: :adjustment_total, other_options: {default: 0.0}},
      # {table: :lisences, column: :price, other_options: {}},
      # {table: :orders, column: :item_total, other_options: {default: 0.0}},
      # {table: :orders, column: :adjustment_total, other_options: {default: 0.0}},
      # {table: :orders, column: :shipment_total, other_options: {default: 0.0}},
      # {table: :orders, column: :total, other_options: {default: 0.0}},
      # {table: :orders, column: :pay_item_total, other_options: {default: 0.0}},
      # {table: :orders, column: :tax_total, other_options: {default: 0.0}},
      # {table: :orders, column: :amount_for_pay, other_options: {default: 0.0}},
      # {table: :orders, column: :vip_discount, other_options: {default: 0.0}},
      # {table: :orders, column: :disable_discount_amount, other_options: {default: 0.0}},
      # {table: :pay_items, column: :amount, other_options: {}},
      # {table: :pay_items, column: :paid_amount, other_options: {default: 0.0}},
      # {table: :pay_items, column: :change, other_options: {default: 0.0}},
      # {table: :payment_logs, column: :amount, other_options: {}},
      {table: :payments, column: :amount, other_options: {}},
      {table: :recharge_products, column: :price, other_options: {default: 100.0}},
      {table: :recharge_products, column: :decimal, other_options: {default: 100.0}},
      {table: :recharge_products, column: :recharge_amount, other_options: {default: 100.0}},
      {table: :recharge_products, column: :first_recharge_available_amount, other_options: {default: 100.0}},
      {table: :reservation_settings, column: :average_consumption, other_options: {default: 30}},
      {table: :service_product_orders, column: :price, other_options: {}},
      {table: :service_product_orders, column: :discount, other_options: {}},
      {table: :service_products, column: :price, other_options: {}},

      {table: :shift_items, column: :amount, other_options: {}},
      {table: :shift_items, column: :cash_amount, other_options: {}},
      {table: :shift_items, column: :extra_amount, other_options: {}},
      {table: :shift_items, column: :actual_amount, other_options: {}},

      {table: :shifts, column: :total_amount, other_options: {}},
      {table: :shifts, column: :total_actual_amount, other_options: {}},
      {table: :shifts, column: :recharge_amount, other_options: {}},
      {table: :shifts, column: :per_capita_consumption, other_options: {}},
      {table: :shifts, column: :per_eat_in_hall_order_consumption, other_options: {}},
      {table: :shifts, column: :total_subtract_item_amount, other_options: {}},
      {table: :shifts, column: :exchange_amount, other_options: {}},
      {table: :shifts, column: :unpaid_amount, other_options: {}},
      {table: :shifts, column: :discount_amount, other_options: {}},
      {table: :shifts, column: :moling_amount, other_options: {}},
      {table: :shifts, column: :recharge_extra_amount, other_options: {}},
      {table: :shifts, column: :vip_card_pay_amount, other_options: {}},

      {table: :shipments, column: :cost, other_options: {}},
      {table: :shop_recharge_records, column: :price, other_options: {}},
      {table: :shops, column: :foreign_tax_rate, other_options: {}},
      {table: :table_zones, column: :min_reservation_price, other_options: {default: 0.0}},
      {table: :table_zones, column: :reservation_price, other_options: {default: 0.0}},
      {table: :tick_account_items, column: :amount, other_options: {}},

      {table: :variants, column: :price, other_options: {}},
      {table: :variants, column: :vip_price, other_options: {}},
      {table: :vip_infos, column: :total_amount, other_options: {default: 0.0}},
      {table: :vip_infos, column: :first_recharge_limited_amount, other_options: {default: 0.0}},

      {table: :vip_levels, column: :upgrade_total_amount, other_options: {}},
      {table: :vip_levels, column: :upgrade_recharge_money, other_options: {}},

      {table: :wallet_logs, column: :amount, other_options: {}},
      {table: :wallet_logs, column: :cash_amount, other_options: {default: 0.0}},
      {table: :wallet_logs, column: :extra_amount, other_options: {default: 0.0}},
      {table: :wallet_logs, column: :balance, other_options: {}},


      {table: :wallets, column: :amount, other_options: {default: 0.0}},
      {table: :wallets, column: :total_recharge_money, other_options: {default: 0.0}},
      {table: :wallets, column: :cash_amount, other_options: {default: 0.0}},
      {table: :wallets, column: :extra_amount, other_options: {default: 0.0}},


    ].each do |msg|
      change_column "ddt_#{msg[:table]}", msg[:column], :decimal, {precision: 10, scale: 2}.merge(msg[:other_options])
    end
  end
end
