# encoding: UTF-8
version = File.read(File.expand_path("../../DIANDANTONG_VERSION", __FILE__)).strip

Gem::Specification.new do |s|
  s.platform    = Gem::Platform::RUBY
  s.name        = 'ddt_core'
  s.version     = version
  s.summary     = 'The bare bones necessary for ddt.'
  s.description = 'The bare bones necessary for ddt.'

  s.required_ruby_version = '>= 1.9.3'
  s.author      = 'ddt'
  s.email       = 'xie_s@diandantong.com'
  s.homepage    = 'http://www.diandantong.com'

  s.files        = Dir["{app,config,db,lib,vendor}/**/*", "Rakefile"]
  s.require_path = 'lib'

  s.add_dependency 'friendly_id'                   , '~> 5.0.0'
  s.add_dependency 'carrierwave'                   , '~> 0.10.0'
  s.add_dependency 'carrierwave-aliyun'            , '~> 0.7.0'
  s.add_dependency 'ckeditor'                      , '~> 4.1.0'
  s.add_dependency 'paranoia'                      , '~> 2.0.2'
  s.add_dependency 'paranoia_uniqueness_validator' , '~> 1.0.1'
  s.add_dependency 'devise'                        , '3.4.0'
  s.add_dependency 'devise-async'                  , '~> 0.9.0'
  s.add_dependency 'cancan'                        , '~> 1.6.10'
  s.add_dependency 'workflow'                      , '~> 1.2.0'
  s.add_dependency 'acts_as_list'                  , '~> 0.4.0'
  s.add_dependency 'ransack'                       , '~> 1.5.1'
  s.add_dependency 'state_machine'                 , '~> 1.2.0'
  s.add_dependency 'rqrcode_png'                   , '~> 0.1.5'
  s.add_dependency 'barby'                         , '~> 0.6.2'
  s.add_dependency 'bcrypt-ruby'                   , '~> 3.0.0'
  s.add_dependency 'sidekiq'                       , '~> 4.1.4'
  s.add_dependency 'will_paginate'                 , '3.0.7'
  s.add_dependency 'sinatra'                       , '>= 1.3.0'
  s.add_dependency 'faraday'                       , '~> 0.9.0'
  s.add_dependency 'multi_logger'                  , '~> 0.1.0'
  s.add_dependency 'httparty'                      , '~> 0.13.0'
  s.add_dependency 'faraday-cookie_jar'            , '~> 0.0.6'
  s.add_dependency 'settingslogic'                 , '~> 2.0.9'
  s.add_dependency 'chinese_cities'                , '~> 0.0.4'
  s.add_dependency 'geocoder'                      , '~> 1.2.5'
  s.add_dependency 'private_pub'                   , '~> 1.0.3'
  s.add_dependency 'rest-client'                   , '~> 1.7.2'
  s.add_dependency 'api-auth'                      , '~> 1.2.6'
  s.add_dependency 'mini_magick'                   , '~> 3.4'
  s.add_dependency 'htmlentities'                  , '~> 4.3.2'
  s.add_dependency 'public_suffix'                 , '~> 1.4.6'
  s.add_dependency 'ruby-pinyin'                   , '~> 0.4.5'
  s.add_dependency 'spreadsheet'                   , '~> 1.0.3'
  s.add_dependency 'yajl-ruby'                     , '~> 1.2.1'
  s.add_dependency 'font-awesome-rails'            , '~> 4.5.0'
  s.add_dependency 'easy_captcha'                  , '~> 0.6.4'
  s.add_dependency 'activerecord-import'           , '~> 0.10.0'
  s.add_dependency 'request_store'                 , '~> 1.2.0'
  s.add_dependency 'rubyzip'                       , '>= 1.0.0'
  s.add_dependency 'jpush'
  s.add_dependency 'redis'                         , '~> 3.2'
end
