zh-CN:
  permission:
    scopes:
      shop: 系统级
      branch: 门店级
    targets:
      account: 账户
      role: 角色
      shop: 系统信息
      branch: 门店
      branch_group: 门店分组
      branch_type: 门店类型
      wechat_account: 微信公众账号
      wechat_config: 微信端设置
      qrcode: 二维码
      sign_record: 微信签到记录
      supply: 物料
      call_setting: 订单呼叫设置
      credits_setting: 积分设置
      ddb_module: 模块
      email_setting: 邮件设置
      short_message_setting: 短信设置
      custom_setting: 自定义设置
      discount_plan: 折扣方案
      zone: 区域
      exchange_code: 兑换码
      gift_reason: 赠菜理由
      subtract_reason: 退菜理由
      merchant_apply: 入驻加盟
      recharge_product: 充值套餐
      recharge_order: 充值订单
      pay_method: 支付方式
      payment_log: 在线支付流水日志
      payment_method: 在线支付设置
      payment: 在线支付明细
      event_promotion: 免赠促销
      order_promotion: 满减优惠
      statistic: 统计
      user: 用户
      vip_level: 会员等级
      card_wallet: 余额管理
      credits_wallet: 积分管理
      collection_wallet: 代收款
      coupon_version: 优惠券
      groupon_version: 团购券
      voucher_version: 代金券
      coupon: 已发放优惠券
      groupon: 已发放团购券
      voucher: 已发放代金券
      arranging_setting: 排号设置
      cs_branch_binding: CS设置
      delivery_setting: 外送设置
      eat_in_hall_setting: 堂点设置
      reservation_setting: 预订设置
      form_element: 自定义表单
      printer: 打印机
      print_record: 打印记录
      print_setting: 打印设置
      bill_template_setting: 打印模版
      queue_setting: 排号队列设置
      guest_queue: 排号客人队列
      comment: 评论
      tag: 标签
      waiter_service_item: 服务项
      cook: 厨师设置
      essential_product: 必选产品
      item_note: 品注
      category: 产品分类
      combo: 套餐
      option_type: 规格类型
      product: 产品
      variant_image: 产品图片
      branch: 门店
      shift: 交班记录
      table_zone: 桌台类型
      table: 桌台
      bill_center: 单据中心
      order: 订单
      delivery_order: 外送订单
      eat_in_hall_order: 堂点订单
      fastfood_order: 快餐订单
      reservation_order: 预定订单
      payment_order: 买单订单
      litp: 菜品
      recharge_order: 充值订单
      tick_account: 挂账单位
      recharge_refund: 充值退款
      feature_modules_config: 功能模块
    actions:
      show:  查看
      create: 创建
      update: 更新
      destroy:  删除
      dashboard: 控制面板
      home: 欢迎页
      clear_data: 清除数据

      manage: 管理
      exchange: 兑换
      statistics_cache: 历史查询
      business_statistic: 营业分析
      coupon_statistic: 券促销分析
      orders_statistic: 订单分析
      product_statistic: 产品分析
      table_statistic: 桌台分析
      user_statistic: 用户分析
      worker_statistic: 工作分析
      finance_statistic: 财务报表
      recharge_card_wallet: 余额充值
      exchange_card_wallet: 余额兑换
      add_discount_plan: 使用折扣方案打折
      cancel_discount_plan: 取消折扣方案打折
      exchange_credits_wallet: 积分兑换
      get_credits_wallet: 积分充值
      send_coupon: 发放优惠卷
      withdraw: 提款
      apply: 使用
      pass: 过号
      accept: 入号
      cancel: 取消
      notify: 通知
      requeue: 重新入号
      reply: 回复
      estimate_clear: 沽清
      open_shift: 开班
      close_shift: 交班
      open: 开台
      bind_table: 绑定桌台
      clear: 清台
      check_out: 拉结账单
      cancel_check_out: 重置结账单
      update_guest_num: 更新客人数量
      check_out: 拉消费单
      force_clear: 强制清台
      discount_list: 折扣清单
      waiter_list: 点菜员清单
      gift_item_list: 赠菜清单
      subtract_item_list: 退菜清单
      sale_list: 销售清单
      payment_list: 第三方支付流水
      shift_list: 交班清单
      combo_package_list: 套餐清单
      order_cancel_list: 订单取消记录
      anti_settlement_list: 反结帐记录
      queue_list: 排号记录
      by_weight_product_list: 称重产品清单
      confirm_line_item_trace_point: 确认菜品烹饪
      cancel_line_item_trace_point: 取消菜品烹饪
      confirm: 确认
      complete: 完成
      reprint: 补打
      settle: 结算
      anti_settlement: 反结算
      append_pay_item: 追加支付条目
      append: 加菜
      gift_item: 赠菜
      subtract: 退菜
      hasten: 催菜
      change_vip_info: 绑定会员
      privilege_discount: 权限折扣
      cancel_privilege_discount: 取消权限折扣
      change_item_price: 单品改价
      change_line_item_weight: 下单后改重量
      batch_change_state: 批量修改状态
      assign_delivery_man: 分配外送员
      start_shipment: 开始配送
      finish_shipment: 完成配送
      change_table: 换台
      merge_table: 并台
      move_itemable: 转菜
      bind_reservation_order: 绑定预订订单
      trace_waiter: 更改服务员
      allow_selfpay: 允许自助买单
      call_customer: 呼叫服务员
      change_to_eat_in_hall: 转为堂点订单
      edit_reservation_info: 编辑预订信息
      add_disabled_promotion: 取消满减优惠
      remove_disabled_promotion: 恢复满减优惠
      confirm_litp: 确认烹饪
      complete_litp: 烹饪完成
      init_refund: 充值退款
      refund: 退款
