export { default as client, setTerminalId, setAuthorizerToken } from './client'
export { authApi } from './modules/auth'
export { shopApi } from './modules/shop'
export { orderApi } from './modules/order'
export { productApi } from './modules/product'
export { cartApi } from './modules/cart'
export { tableApi } from './modules/table'
export { printerApi } from './modules/printer'
export { vipInfoApi } from './modules/vip-info'
export { queueApi } from './modules/queue'
export { billApi } from './modules/bill'
export { statisticApi } from './modules/statistic'
export { notificationApi } from './modules/notification'
export { couponApi } from './modules/coupon'
export { discountPlanApi } from './modules/discount-plan'
export { formElementApi } from './modules/form-element'
